spring:
  config:
    profiles: docker
    activate:
      on-profile: docker
  application:
    name: order-aggregator-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak-tenflix:8080/realms/tenflix/protocol/openid-connect/certs
  

# grpc
grpc:
  client:
    order-service:
      address: static://order-service:9002
      negotiation-type: plaintext
    payment-service:
      address: static://payment-service:9003
      negotiation-type: plaintext
    subscription-service:
      address: static://subscription-service:9000
      negotiation-type: plaintext
    user-service:
      address: static://user-service:9001
      negotiation-type: plaintext
  
  
server:
  port: 9200

# keycloak
keycloak:
  realm: tenflix
  resource: tenflix-client
  auth-server-url: http://keyloak-tenflix:8080
